- name: PLAY-01
  hosts: front
  tasks:
  - name: PLAY-01 TASK-01
    ansible.builtin.debug:
      msg: "This is from PLAY-01 and TASK-01"

- name: PLAY-02
  hosts: front
  tasks:
  - name: PLAY-02 TASK-02
    ansible.builtin.debug:
      msg: "hi this is prabhakar"      