- name: loops demo
  hosts: fornt
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present 
    loop:
    - mysql
    - nginx
    - postfix
    - httpd